# Generated by Django 5.0.1 on 2024-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
