# Generated by Django 5.0.1 on 2024-01-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
