# Generated by Django 5.0.1 on 2024-01-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_img_image_file_image_alt_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
